set nocompatible
set wrap linebreak nolist
set formatoptions+=t
set ruler
set backspace=indent,eol,start
set autoindent
set showmode
set viminfo='20,\"50
set autowrite
set showmatch
set showcmd
set ignorecase
set incsearch
syn on
set vb
set wildmenu
set number
set paste
set textwidth=80
set encoding=utf-8
set shiftwidth=4
set softtabstop=4
set tabstop=4
syntax on
set term=xterm-256color
set listchars=space:·,eol:$,tab:>-,trail:~,extends:>,precedes:<
let &colorcolumn=join(range(80,80),",")
map <C-n> :tabnew<CR>
map <TAB> :tabnext<CR>
map <S-TAB> :tabprevious<CR>
map <C-p> :FZF<CR>
"autocmd BufWritePre * %s/\s\+$//e
set clipboard=unnamed
autocmd FileType c,cpp setlocal equalprg=clang-format
set spell

call plug#begin()
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()
