set nocompatible
set wrap linebreak nolist
set formatoptions+=t
set ruler
set backspace=indent,eol,start
set autoindent
set showmode
set viminfo='20,\"50
set autowrite
set showmatch
set showcmd
set ignorecase
set incsearch
syn on
set vb
set wildmenu
set number
set paste
colorscheme dracula
set textwidth=80
set encoding=utf-8
set shiftwidth=4
set softtabstop=4
set tabstop=4
syntax on
set term=xterm-256color

map <C-n> :tabnew<CR>
map <C-e> :edit
map <TAB> :tabnext<CR>
map <S-TAB> :tabprevious<CR>
map <leader>s :set list!

set listchars=space:·

let &colorcolumn=join(range(80,80),",")
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

set ai

function! Whitespace()
    if !exists('b:ws')
        highlight Conceal ctermbg=NONE ctermfg=240 cterm=NONE guibg=NONE guifg=#585858 gui=NONE
        highlight link Whitespace Conceal
        let b:ws = 1
    endif

    syntax match Whitespace / / containedin=ALL conceal cchar=·
    setlocal conceallevel=2 concealcursor=c
endfunction

augroup Whitespace
    autocmd!
    autocmd BufEnter,WinEnter * call Whitespace()
augroup END
