HISTFILE=~/.histfile
HISTSIZE=1000000000
SAVEHIST=1000000000
setopt appendhistory
setopt extendedhistory
setopt print_exit_value
unsetopt promptcr

export PAGER=less
export EDITOR="vim"
export VISUAL="vim"
export LESS="-X"
export LC_TIME="lt_LT.UTF-8"
export LC_COLLATE="lt_LT.UTF-8"

#export IGNOREEOF=0

# bash like ctrl-d wrapper for IGNOREEOF
setopt ignore_eof
function bash-ctrl-d() {
  if [[ $CURSOR == 0 && -z $BUFFER ]]
  then
    [[ -z $IGNOREEOF || $IGNOREEOF == 0 ]] && exit
    if [[ "$LASTWIDGET" == "bash-ctrl-d" ]]
    then
      (( --__BASH_IGNORE_EOF <= 0 )) && exit
    else
      (( __BASH_IGNORE_EOF = IGNOREEOF ))
    fi
  fi
}
zle -N bash-ctrl-d
bindkey "^d" bash-ctrl-d

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/home/bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims"
export LC_ALL="en_US.UTF-8"

bindkey -e

bindkey "^[OA" up-line-or-search
bindkey "^[OB" down-line-or-search

bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward

setopt auto_pushd
DIRSTACKSIZE=50

alias ping='ping -n '

PS1="%B[%T]%b %U%M%u %n %d
%# "

setopt extendedglob
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z} m:[-._]=[-._] r:|[-./_]=** r:|=*' '+l:|=*' #csh “set complete=enhance”

#title stuff
function title {
  if [[ $TERM == "screen" ]]; then
    # Use these two for GNU Screen:
    print -nR $'\033k'$1$'\033'\\\

    print -nR $'\033]0;'$2$'\a'
  elif [[ $TERM == "xterm" || $TERM == "rxvt" ]]; then
    # Use this one instead for XTerms:
    print -nR $'\033]0;'$*$'\a'
  fi
}

function precmd {
  title zsh "$PWD"
}

function preexec {
  emulate -L zsh
  local -a cmd; cmd=(${(z)1})
  title $cmd[1]:t "$cmd[2,-1]"
}

if [[ -r /etc/zsh_command_not_found ]]; then
  . /etc/zsh_command_not_found
fi

# git stuff (show branch)
zstyle ':vcs_info:git*' formats "%r/%S [%b] (%a) %m%u%c"
autoload -Uz vcs_info
precmd () { vcs_info }
setopt prompt_subst
PS1="\$vcs_info_msg_0_$PS1"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

VAULT_TOKEN_FILE="$HOME/.vault-token"
if [[ ! -f "$VAULT_TOKEN_FILE" ]] || (( $(date +%s) - $(stat -c %Y "$VAULT_TOKEN_FILE") > 21600 )); then
    vault login -address=https://FIXME -field=token -method=oidc role=google
fi
export VAULT_TOKEN=$(cat "$VAULT_TOKEN_FILE")
export VAULT_AUTH_METHOD=token
export VAULT_ADDR=https://FIXME
export ANSIBLE_STRATEGY=mitogen_linear
export ANSIBLE_STRATEGY_PLUGINS=/usr/lib/python3/dist-packages/ansible_mitogen/plugins/strategy

[ -f ~/.ssh/agent.env ] && source ~/.ssh/agent.env

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. "$HOME/.local/bin/env"
