- name: Set email
  git_config:
    name: user.email
    scope: global
    value: donatas.abraitis@gmail.com

- name: Set name
  git_config:
    name: user.name
    scope: global
    value: Donatas Abraitis

- name: Set default editor
  git_config:
    name: core.editor
    scope: global
    value: vim

- name: Avoid ESC[ crap
  git_config:
    name: core.pager
    scope: global
    value: less -r
