- name: Install official OpenRazer driver
  apt_repository:
    repo: 'ppa:openrazer/stable'

- name: Install openrazer-meta
  apt:
    name: openrazer-meta

- name: Add razer repo
  apt_repository:
    repo: 'ppa:nilarimogard/webupd8'

- name: Install razer tools
  apt:
    name: "{{ item }}"
  with_items:
    - razercfg
    - qrazercfg
    - qrazercfg-applet

- name: Make sure razerd service is started and enabled
  service:
    name: razerd
    enabled: yes
    state: started
