- name: Add l2tp repo
  apt_repository:
    repo: 'ppa:nm-l2tp/network-manager-l2tp'

- name: Install basic tools
  apt:
    name: "{{ item }}"
  with_items:
  - maim
  - neovim-qt
  - i3
  - guake
  - zsh
  - git
  - vim
  - curl
  - irssi
  - tmux
  - ruby-build
  - cmake
  - build-essential
  - libcurl4-openssl-dev
  - libjansson-dev
  - libsdl2-dev
  - libpng-dev
  - libjpeg-dev
  - libexpat1-dev
  - libspeex-dev
  - libspeexdsp-dev
  - wine-stable
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - gnome-control-center
  - gnome-online-accounts
  - autoconf
  - autogen
  - libtool
  - ipcalc
  - pwgen
  - whois
  - traceroute
  - nghttp2-client
  - golang-go
  - golang-golang-x-tools
  - nmap
  - pavucontrol
  - minicom
  - xinetd
  - gimp
  - graphviz
  - tig
  - pv
  - icedtea-netx
  - tilix
  - clang-format-18
  - xml2rfc
  - devscripts
  - virtualbox
  - libreadline-dev
  - texinfo
  - coccinelle

- name: Install discord
  snap:
    name: discord
    classic: yes

- name: Install slack
  snap:
    name: slack
    classic: yes

- name: Install Remmina RDP client
  snap:
    name: remmina

- name: Install shodan cli
  pip:
    name: shodan

- name: Change default shell
  user:
    name: donatas
    shell: /bin/zsh

- name: Configure zsh
  copy:
    src: zshrc
    dest: ~/.zshrc

- name: Configure vim
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Configure Guake
  copy:
    src: guake_preferences
    dest: ~/.guake

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Set default shell to /bin/zsh
  user:
    name: donatas
    shell: /bin/zsh

- name: Copy tilix.dconf
  copy:
    src: tilix.dconf
    dest: ~/.tilix.dconf

- name: Load tilix.dconf
  shell: dconf load /com/gexperts/Tilix/ < ~/.tilix.dconf

- name: Copy Visual Studio Code settings
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json

- name: Copy .irssi/config
  copy:
    src: irssi/config
    dest: ~/.irssi/config
