- name: Add l2tp repo
  apt_repository:
    repo: 'ppa:nm-l2tp/network-manager-l2tp'

- name: Install basic tools
  apt:
    name: "{{ item }}"
  with_items:
  - zsh
  - git
  - vim
  - curl
  - irssi
  - tmux
  - ruby-build
  - cmake
  - build-essential
  - libcurl4-openssl-dev
  - libjansson-dev
  - libsdl2-dev
  - libpng-dev
  - libjpeg-dev
  - libexpat1-dev
  - libspeex-dev
  - libspeexdsp-dev
  - wine
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - network-manager-openvpn

- name: Change default shell
  user:
    name: donatas
    shell: /bin/zsh

- name: Configure zsh
  copy:
    src: zshrc
    dest: ~/.zshrc

- name: Create ~/.vim/colors directory
  file:
    path: ~/.vim/colors
    state: directory
    recurse: true

- name: Download dracula theme
  get_url:
    url: https://raw.githubusercontent.com/dracula/vim/master/colors/dracula.vim
    dest: ~/.vim/colors/dracula.vim

- name: Configure vim
  copy:
    src: vimrc
    dest: ~/.vimrc
