- name: Add l2tp repo
  apt_repository:
    repo: 'ppa:nm-l2tp/network-manager-l2tp'

- name: Install basic tools
  apt:
    name: "{{ item }}"
  with_items:
  - python-pip
  - zsh
  - git
  - vim
  - curl
  - irssi
  - tmux
  - ruby-build
  - cmake
  - build-essential
  - libcurl4-openssl-dev
  - libjansson-dev
  - libsdl2-dev
  - libpng-dev
  - libjpeg-dev
  - libexpat1-dev
  - libspeex-dev
  - libspeexdsp-dev
  - wine-stable
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - gnome-control-center
  - gnome-online-accounts
  - autoconf
  - autogen
  - libtool
  - ipcalc
  - pwgen
  - whois
  - traceroute
  - python-netaddr
  - nghttp2-client
  - golang-go
  - golang-golang-x-tools
  - nmap
  - pavucontrol
  - minicom
  - xinetd
  - tftp
  - tftpd
  - gimp
  - graphviz
  - tig
  - pv
  - icedtea-netx

- name: Install shodan cli
  pip:
    name: shodan

- name: Change default shell
  user:
    name: donatas
    shell: /bin/zsh

- name: Configure zsh
  copy:
    src: zshrc
    dest: ~/.zshrc

- name: Create ~/.vim/colors directory
  file:
    path: ~/.vim/colors
    state: directory
    recurse: true

- name: Download dracula theme
  get_url:
    url: https://raw.githubusercontent.com/dracula/vim/master/colors/dracula.vim
    dest: ~/.vim/colors/dracula.vim

- name: Configure vim
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Add spotify repo
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'

- name: Install spotify-client
  apt:
    name: spotify-client
